# shellcheck shell=sh
# Opt-in single-card AIU collapse. Setting `-e SPYRE_SINGLE_CARD_BDF=<bdf>`
# at `podman run` time overrides the host-autogenerated multi-card AIU_WORLD_*
# config with a single-rank world pinned to that PCI BDF. Required when the
# host has N>1 AIUs but only one VFIO group is mapped into the container via
# --device — otherwise senlib tries to open /dev/vfio/<grp> for every card
# and dies with RAS 0x332b "DeviceOpenFail" on the missing ones.
#
# Unset: no-op; the host autogen multi-card config is preserved (production
# serving path).
if [ -n "${SPYRE_SINGLE_CARD_BDF}" ]; then
  for v in $(env | grep -oE '^AIU_(WORLD|TIER_[01])_[A-Z0-9_]+'); do
    unset "$v"
  done
  export AIU_WORLD_SIZE=1
  export AIU_WORLD_RANK_0="${SPYRE_SINGLE_CARD_BDF}"
  export AIU_TIER_0_NUM_SETS=1
  export AIU_TIER_0_SET_0_SIZE=1
  export AIU_TIER_0_SET_0_RANK_0="${SPYRE_SINGLE_CARD_BDF}"
  export AIU_TIER_1_NUM_SETS=1
  export AIU_TIER_1_SET_0_SIZE=1
  export AIU_TIER_1_SET_0_RANK_0="${SPYRE_SINGLE_CARD_BDF}"
fi